update boot cmd and first login

diff --git a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
--- a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
+++ b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
@@ -681,6 +681,8 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	# Try to get the local IP address (script halts until IP was found or x retries were done)
 	get_local_ip_addr
 
+	PRESET_ROOT_PASSWORD="shushi16888"
+
 	[[ -z "$PRESET_ROOT_PASSWORD" ]] && echo "" # empty line
 
 	trap '' 2
@@ -764,173 +766,175 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 
 	trap check_abort INT
 
-	while [ -f "/root/.not_logged_in_yet" ]; do
-		[[ -z "${PRESET_USER_NAME}" ]] && echo -e "\nCreating a new user account. Press <Ctrl-C> to abort"
-		[[ "${desktop_dm}" != "none" ]] && echo -e "\n\e[0;31mDesktop environment will not be enabled if you abort the new user creation\x1B[0m"
-		add_user
-	done
-	trap - INT TERM EXIT
+	rm -f /root/.not_logged_in_yet
 
-	# ask user to select automated locales or not
-	trap '' 2
-	set_timezone_and_locales
-	trap - INT TERM EXIT
+	# while [ -f "/root/.not_logged_in_yet" ]; do
+	# 	[[ -z "${PRESET_USER_NAME}" ]] && echo -e "\nCreating a new user account. Press <Ctrl-C> to abort"
+	# 	[[ "${desktop_dm}" != "none" ]] && echo -e "\n\e[0;31mDesktop environment will not be enabled if you abort the new user creation\x1B[0m"
+	# 	add_user
+	# done
+	# trap - INT TERM EXIT
 
-	if [[ ${USER_SHELL} == zsh ]]; then
-		printf "\nYou selected \e[0;91mZSH\x1B[0m as your default shell. If you want to use it right away, please logout and login! \n\n"
-	fi
+	# # ask user to select automated locales or not
+	# trap '' 2
+	# set_timezone_and_locales
+	# trap - INT TERM EXIT
 
-	# re-enable passing locale environment via ssh
-	sed -e '/^#AcceptEnv LANG/ s/^#//' -i /etc/ssh/sshd_config
-	# restart sshd daemon
-	systemctl restart ssh.service
+	# if [[ ${USER_SHELL} == zsh ]]; then
+	# 	printf "\nYou selected \e[0;91mZSH\x1B[0m as your default shell. If you want to use it right away, please logout and login! \n\n"
+	# fi
 
-	# rpardini: hacks per-dm, very much legacy stuff that works by a miracle
-	if [[ "${desktop_dm}" == "lightdm" ]] && [ -n "$RealName" ]; then
+	# # re-enable passing locale environment via ssh
+	# sed -e '/^#AcceptEnv LANG/ s/^#//' -i /etc/ssh/sshd_config
+	# # restart sshd daemon
+	# systemctl restart ssh.service
 
-		mkdir -p /etc/lightdm/lightdm.conf.d
-		cat <<- EOF > /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
-			[Seat:*]
-			autologin-user=$RealUserName
-			autologin-user-timeout=0
-			user-session=xfce
-		EOF
+	# # rpardini: hacks per-dm, very much legacy stuff that works by a miracle
+	# if [[ "${desktop_dm}" == "lightdm" ]] && [ -n "$RealName" ]; then
 
-		# select gnome session (has to be first or it breaks budgie/cinnamon desktop autologin and user-session)
-		# @TODO: remove this, gnome should use gdm3, not lightdm
-		[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	mkdir -p /etc/lightdm/lightdm.conf.d
+	# 	cat <<- EOF > /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		[Seat:*]
+	# 		autologin-user=$RealUserName
+	# 		autologin-user-timeout=0
+	# 		user-session=xfce
+	# 	EOF
 
-		# select awesome session
-		[[ -x $(command -v awesome) ]] && sed -i "s/user-session.*/user-session=awesome/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v awesome) ]] && sed -i "s/user-session.*/user-session=awesome/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select gnome session (has to be first or it breaks budgie/cinnamon desktop autologin and user-session)
+	# 	# @TODO: remove this, gnome should use gdm3, not lightdm
+	# 	[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select budgie session
-		[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select awesome session
+	# 	[[ -x $(command -v awesome) ]] && sed -i "s/user-session.*/user-session=awesome/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v awesome) ]] && sed -i "s/user-session.*/user-session=awesome/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select cinnamon session
-		[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select budgie session
+	# 	[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select deepin session
-		[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select cinnamon session
+	# 	[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select ice-wm session
-		[[ -x $(command -v icewm-session) ]] && sed -i "s/user-session.*/user-session=icewm-session/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v icewm-session) ]] && sed -i "s/user-session.*/user-session=icewm-session/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select deepin session
+	# 	[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select i3 session
-		[[ -x $(command -v i3) ]] && sed -i "s/user-session.*/user-session=i3/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v i3) ]] && sed -i "s/user-session.*/user-session=i3/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select ice-wm session
+	# 	[[ -x $(command -v icewm-session) ]] && sed -i "s/user-session.*/user-session=icewm-session/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v icewm-session) ]] && sed -i "s/user-session.*/user-session=icewm-session/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select lxde session
-		[[ -x $(command -v startlxde) ]] && sed -i "s/user-session.*/user-session=LXDE/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v startlxde) ]] && sed -i "s/user-session.*/user-session=LXDE/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select i3 session
+	# 	[[ -x $(command -v i3) ]] && sed -i "s/user-session.*/user-session=i3/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v i3) ]] && sed -i "s/user-session.*/user-session=i3/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select lxqt session
-		[[ -x $(command -v startlxqt) ]] && sed -i "s/user-session.*/user-session=lxqt/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v startlxqt) ]] && sed -i "s/user-session.*/user-session=lxqt/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select lxde session
+	# 	[[ -x $(command -v startlxde) ]] && sed -i "s/user-session.*/user-session=LXDE/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v startlxde) ]] && sed -i "s/user-session.*/user-session=LXDE/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select mate session
-		[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select lxqt session
+	# 	[[ -x $(command -v startlxqt) ]] && sed -i "s/user-session.*/user-session=lxqt/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v startlxqt) ]] && sed -i "s/user-session.*/user-session=lxqt/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select sway wayland session
-		[[ -x $(command -v sway) ]] && sed -i "s/user-session.*/user-session=sway/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v sway) ]] && sed -i "s/user-session.*/user-session=sway/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select mate session
+	# 	[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		# select xmonad session
-		[[ -x $(command -v xmonad) ]] && sed -i "s/user-session.*/user-session=xmonad/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-		[[ -x $(command -v xmonad) ]] && sed -i "s/user-session.*/user-session=xmonad/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 	# select sway wayland session
+	# 	[[ -x $(command -v sway) ]] && sed -i "s/user-session.*/user-session=sway/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v sway) ]] && sed -i "s/user-session.*/user-session=sway/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		ln -sf /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service
+	# 	# select xmonad session
+	# 	[[ -x $(command -v xmonad) ]] && sed -i "s/user-session.*/user-session=xmonad/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 	[[ -x $(command -v xmonad) ]] && sed -i "s/user-session.*/user-session=xmonad/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-		if [[ -f /var/run/resize2fs-reboot ]]; then
-			# Let the user reboot now otherwise start desktop environment
-			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
-		else
-			echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
-			sleep 1
-			service lightdm start 2> /dev/null
-			if [ -f /root/.desktop_autologin ]; then
-				rm /root/.desktop_autologin
-			else
-				systemctl -q enable armbian-disable-autologin.timer
-				systemctl start armbian-disable-autologin.timer
-			fi
-			# logout if logged at console
-			who -la | grep root | grep -q tty1 && exit 1
-		fi
+	# 	ln -sf /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service
 
-	elif [[ "${desktop_dm}" == "gdm3" ]] && [ -n "$RealName" ]; then
-		# 1st run goes without login
-		mkdir -p /etc/gdm3
-		cat <<- EOF > /etc/gdm3/custom.conf
-			[daemon]
-			AutomaticLoginEnable = true
-			AutomaticLogin = $RealUserName
-		EOF
+	# 	if [[ -f /var/run/resize2fs-reboot ]]; then
+	# 		# Let the user reboot now otherwise start desktop environment
+	# 		printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+	# 		printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+	# 	else
+	# 		echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
+	# 		sleep 1
+	# 		service lightdm start 2> /dev/null
+	# 		if [ -f /root/.desktop_autologin ]; then
+	# 			rm /root/.desktop_autologin
+	# 		else
+	# 			systemctl -q enable armbian-disable-autologin.timer
+	# 			systemctl start armbian-disable-autologin.timer
+	# 		fi
+	# 		# logout if logged at console
+	# 		who -la | grep root | grep -q tty1 && exit 1
+	# 	fi
 
-		ln -sf /lib/systemd/system/gdm3.service /etc/systemd/system/display-manager.service
+	# elif [[ "${desktop_dm}" == "gdm3" ]] && [ -n "$RealName" ]; then
+	# 	# 1st run goes without login
+	# 	mkdir -p /etc/gdm3
+	# 	cat <<- EOF > /etc/gdm3/custom.conf
+	# 		[daemon]
+	# 		AutomaticLoginEnable = true
+	# 		AutomaticLogin = $RealUserName
+	# 	EOF
 
-		if [[ -f /var/run/resize2fs-reboot ]]; then
-			# Let the user reboot now otherwise start desktop environment
-			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
-		else
-			echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
-			sleep 1
-			service gdm3 start 2> /dev/null
-			if [ -f /root/.desktop_autologin ]; then
-				rm /root/.desktop_autologin
-			else
-				(
-					sleep 20
-					sed -i "s/AutomaticLoginEnable.*/AutomaticLoginEnable = false/" /etc/gdm3/custom.conf
-				) &
-			fi
-			# logout if logged at console
-			who -la | grep root | grep -q tty1 && exit 1
-		fi
-	elif [[ "${desktop_dm}" == "sddm" ]] && [ -n "$RealName" ]; then
+	# 	ln -sf /lib/systemd/system/gdm3.service /etc/systemd/system/display-manager.service
 
-		# create default sddm config
-		mkdir -p /etc/sddm.conf.d
-		cat <<- EOF > /etc/sddm.conf.d/armbian.conf
-			[Theme]
-			Current=breeze
-			[General]
-			InputMethod=none
-		EOF
+	# 	if [[ -f /var/run/resize2fs-reboot ]]; then
+	# 		# Let the user reboot now otherwise start desktop environment
+	# 		printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+	# 		printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+	# 	else
+	# 		echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
+	# 		sleep 1
+	# 		service gdm3 start 2> /dev/null
+	# 		if [ -f /root/.desktop_autologin ]; then
+	# 			rm /root/.desktop_autologin
+	# 		else
+	# 			(
+	# 				sleep 20
+	# 				sed -i "s/AutomaticLoginEnable.*/AutomaticLoginEnable = false/" /etc/gdm3/custom.conf
+	# 			) &
+	# 		fi
+	# 		# logout if logged at console
+	# 		who -la | grep root | grep -q tty1 && exit 1
+	# 	fi
+	# elif [[ "${desktop_dm}" == "sddm" ]] && [ -n "$RealName" ]; then
 
-		# 1st run goes without login
-		cat <<- EOF > /etc/sddm.conf.d/autologin.conf
-			[Autologin]
-			User=$RealUserName
-		EOF
-		echo -e "\n\e[1m\e[39mNow starting desktop environment via ${desktop_dm}...\x1B[0m\n"
-		systemctl enable --now sddm 2> /dev/null
+	# 	# create default sddm config
+	# 	mkdir -p /etc/sddm.conf.d
+	# 	cat <<- EOF > /etc/sddm.conf.d/armbian.conf
+	# 		[Theme]
+	# 		Current=breeze
+	# 		[General]
+	# 		InputMethod=none
+	# 	EOF
 
-		if [ -f /root/.desktop_autologin ]; then
-				rm /root/.desktop_autologin
-		else
-			systemctl -q enable armbian-disable-autologin.timer
-		fi
-		# logout if logged at console
-		who -la | grep root | grep -q tty1 && exit 1
+	# 	# 1st run goes without login
+	# 	cat <<- EOF > /etc/sddm.conf.d/autologin.conf
+	# 		[Autologin]
+	# 		User=$RealUserName
+	# 	EOF
+	# 	echo -e "\n\e[1m\e[39mNow starting desktop environment via ${desktop_dm}...\x1B[0m\n"
+	# 	systemctl enable --now sddm 2> /dev/null
 
-	else
-		# no display manager detected -> clear screen and show motd
-		clear
-		run-parts --lsbsysinit /etc/update-motd.d
+	# 	if [ -f /root/.desktop_autologin ]; then
+	# 			rm /root/.desktop_autologin
+	# 	else
+	# 		systemctl -q enable armbian-disable-autologin.timer
+	# 	fi
+	# 	# logout if logged at console
+	# 	who -la | grep root | grep -q tty1 && exit 1
 
-		# Display reboot recommendation if necessary
-		if [[ -f /var/run/resize2fs-reboot ]]; then
-			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
-		fi
-	fi
+	# else
+	# 	# no display manager detected -> clear screen and show motd
+	# 	clear
+	# 	run-parts --lsbsysinit /etc/update-motd.d
+
+	# 	# Display reboot recommendation if necessary
+	# 	if [[ -f /var/run/resize2fs-reboot ]]; then
+	# 		printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+	# 		printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+	# 	fi
+	# fi
 fi
