update auto-login for first boot and network remote setting

diff --git a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
--- a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
+++ b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
@@ -73,23 +73,23 @@ set_shell()
 	optionsAudits=($(grep "zsh\|/bash" /etc/shells | sed 's/\/bin\///g' | sed 's/\/usr//g' | uniq))
 	USER_SHELL="bash"
 
-	if [[ "${#optionsAudits[@]}" -gt 1 ]]; then
-		while :
-			do
-				i=1
-				echo -e "\nChoose default system command shell:\n"
-				for o in  "${optionsAudits[@]}"; do
-					echo "$i) $o"
-					let i++
-				done
-				read -n1 -s reply
-				case $reply in
-					"1"|"${optionsAudits[0]}") USER_SHELL="${optionsAudits[0]}"; break;;
-					"2"|"${optionsAudits[1]}") USER_SHELL="${optionsAudits[1]}"; break;;
-					*) USER_SHELL="${optionsAudits[0]}"; break;;
-				esac
-			done
-	fi
+	# if [[ "${#optionsAudits[@]}" -gt 1 ]]; then
+	# 	while :
+	# 		do
+	# 			i=1
+	# 			echo -e "\nChoose default system command shell:\n"
+	# 			for o in  "${optionsAudits[@]}"; do
+	# 				echo "$i) $o"
+	# 				let i++
+	# 			done
+	# 			read -n1 -s reply
+	# 			case $reply in
+	# 				"1"|"${optionsAudits[0]}") USER_SHELL="${optionsAudits[0]}"; break;;
+	# 				"2"|"${optionsAudits[1]}") USER_SHELL="${optionsAudits[1]}"; break;;
+	# 				*) USER_SHELL="${optionsAudits[0]}"; break;;
+	# 			esac
+	# 		done
+	# fi
 	SHELL_PATH=$(grep /$USER_SHELL$ /etc/shells | tail -1)
 
 	chsh -s $(grep -iF "/$USER_SHELL" /etc/shells | tail -1)
@@ -301,9 +301,9 @@ add_user()
 
 if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	# disable autologin
-	rm -f /etc/systemd/system/getty@.service.d/override.conf
-	rm -f /etc/systemd/system/serial-getty@.service.d/override.conf
-	systemctl daemon-reload
+	#rm -f /etc/systemd/system/getty@.service.d/override.conf
+	#rm -f /etc/systemd/system/serial-getty@.service.d/override.conf
+	#systemctl daemon-reload
 
 	# detect display manager
 	desktop_lightdm=$(dpkg-query -W -f='${db:Status-Abbrev}\n' lightdm 2>/dev/null)
@@ -333,7 +333,8 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	REPEATS=3
 	while [ -f "/root/.not_logged_in_yet" ]; do
 
-		read_password "Create root"
+		password="shushi6688"
+		#read_password "Create root"
 
 		# only allow one login. Once you enter root password, kill others.
 		loginfrom=$(who am i | awk '{print $2}')
@@ -341,7 +342,7 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 
 		first_input="$password"
 		echo ""
-		read_password "Repeat root"
+		#read_password "Repeat root"
 		second_input="$password"
 		echo ""
 		if [[ "$first_input" == "$second_input" ]]; then
@@ -387,121 +388,125 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	set_shell
 	trap - INT TERM EXIT
 
+
 	trap check_abort INT
 
-	while [ -f "/root/.not_logged_in_yet" ]; do
-		echo -e "\nCreating a new user account. Press <Ctrl-C> to abort"
-		[ -n "$desktop_lightdm" ] && echo -e "\n\e[0;31mDesktop environment will not be enabled if you abort the new user creation\x1B[0m"
-		add_user
-	done
-	trap - INT TERM EXIT
 
-	# ask user to select automated locales or not
-	trap '' 2
-	set_timezone_and_locales
-	trap - INT TERM EXIT
+	rm -f /root/.not_logged_in_yet
 
-	if [[ ${USER_SHELL} == zsh ]]; then
-		printf "\nYou selected \e[0;91mZSH\x1B[0m as your default shell. If you want to use it right away, please logout and login! \n\n"
-	fi
+	# while [ -f "/root/.not_logged_in_yet" ]; do
+	# 	echo -e "\nCreating a new user account. Press <Ctrl-C> to abort"
+	# 	[ -n "$desktop_lightdm" ] && echo -e "\n\e[0;31mDesktop environment will not be enabled if you abort the new user creation\x1B[0m"
+	# 	add_user
+	# done
+	# trap - INT TERM EXIT
 
-	# check whether desktop environment has to be considered
-	if [ -n "$desktop_lightdm" ] && [ -n "$RealName" ] ; then
+	# # ask user to select automated locales or not
+	# trap '' 2
+	# set_timezone_and_locales
+	# trap - INT TERM EXIT
 
-			# 1st run goes without login
-			mkdir -p /etc/lightdm/lightdm.conf.d
-			cat <<-EOF > /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
-			[Seat:*]
-			autologin-user=$RealUserName
-			autologin-user-timeout=0
-			user-session=xfce
-			EOF
+	# if [[ ${USER_SHELL} == zsh ]]; then
+	# 	printf "\nYou selected \e[0;91mZSH\x1B[0m as your default shell. If you want to use it right away, please logout and login! \n\n"
+	# fi
 
-			# select gnome session (has to be first or it breaks budgie/cinnamon desktop autologin and user-session)
-			[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-			[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# # check whether desktop environment has to be considered
+	# if [ -n "$desktop_lightdm" ] && [ -n "$RealName" ] ; then
 
-			# select budgie session
-			[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-			[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		# 1st run goes without login
+	# 		mkdir -p /etc/lightdm/lightdm.conf.d
+	# 		cat <<-EOF > /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		[Seat:*]
+	# 		autologin-user=$RealUserName
+	# 		autologin-user-timeout=0
+	# 		user-session=xfce
+	# 		EOF
 
-			# select deepin session
-			[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-			[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		# select gnome session (has to be first or it breaks budgie/cinnamon desktop autologin and user-session)
+	# 		[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 		[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-			# select cinnamon session
-			[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-			[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		# select budgie session
+	# 		[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 		[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-			# select mate session
-			[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-			[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		# select deepin session
+	# 		[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 		[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-                        # select plasma wayland session
-                        [[ -x $(command -v plasmashell) ]] && sed -i "s/user-session.*/user-session=plasmawayland/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
-                        [[ -x $(command -v plasmashell) ]] && sed -i "s/user-session.*/user-session=plasmawayland/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+	# 		# select cinnamon session
+	# 		[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 		[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-			ln -sf /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service
+	# 		# select mate session
+	# 		[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+	# 		[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-			if [[ -f /var/run/resize2fs-reboot ]]; then
-				# Let the user reboot now otherwise start desktop environment
-				printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-				printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
-			elif [ -z "$ConfigureDisplay" ] || [ "$ConfigureDisplay" = "n" ] || [ "$ConfigureDisplay" = "N" ]; then
-				echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
-				sleep 1
-				service lightdm start 2>/dev/null
-				if [ -f /root/.desktop_autologin ]; then
-					rm /root/.desktop_autologin
-				else
-					systemctl -q enable armbian-disable-autologin.timer
-					systemctl start armbian-disable-autologin.timer
-				fi
-				# logout if logged at console
-				[[ -n $(who -la | grep root | grep tty1) ]] && exit 1
-			fi
+    #                     # select plasma wayland session
+    #                     [[ -x $(command -v plasmashell) ]] && sed -i "s/user-session.*/user-session=plasmawayland/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+    #                     [[ -x $(command -v plasmashell) ]] && sed -i "s/user-session.*/user-session=plasmawayland/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
 
-	elif [ -n "$desktop_gdm3" ] && [ -n "$RealName" ] ; then
+	# 		ln -sf /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service
 
-			# 1st run goes without login
-			mkdir -p /etc/gdm3
-			cat <<-EOF > /etc/gdm3/custom.conf
-			[daemon]
-			AutomaticLoginEnable = true
-			AutomaticLogin = $RealUserName
-			EOF
+	# 		if [[ -f /var/run/resize2fs-reboot ]]; then
+	# 			# Let the user reboot now otherwise start desktop environment
+	# 			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+	# 			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+	# 		elif [ -z "$ConfigureDisplay" ] || [ "$ConfigureDisplay" = "n" ] || [ "$ConfigureDisplay" = "N" ]; then
+	# 			echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
+	# 			sleep 1
+	# 			service lightdm start 2>/dev/null
+	# 			if [ -f /root/.desktop_autologin ]; then
+	# 				rm /root/.desktop_autologin
+	# 			else
+	# 				systemctl -q enable armbian-disable-autologin.timer
+	# 				systemctl start armbian-disable-autologin.timer
+	# 			fi
+	# 			# logout if logged at console
+	# 			[[ -n $(who -la | grep root | grep tty1) ]] && exit 1
+	# 		fi
 
-			ln -sf /lib/systemd/system/gdm3.service /etc/systemd/system/display-manager.service
+	# elif [ -n "$desktop_gdm3" ] && [ -n "$RealName" ] ; then
 
-				if [[ -f /var/run/resize2fs-reboot ]]; then
+	# 		# 1st run goes without login
+	# 		mkdir -p /etc/gdm3
+	# 		cat <<-EOF > /etc/gdm3/custom.conf
+	# 		[daemon]
+	# 		AutomaticLoginEnable = true
+	# 		AutomaticLogin = $RealUserName
+	# 		EOF
 
-					# Let the user reboot now otherwise start desktop environment
-					printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-					printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+	# 		ln -sf /lib/systemd/system/gdm3.service /etc/systemd/system/display-manager.service
 
-				elif [ -z "$ConfigureDisplay" ] || [ "$ConfigureDisplay" = "n" ] || [ "$ConfigureDisplay" = "N" ]; then
+	# 			if [[ -f /var/run/resize2fs-reboot ]]; then
 
-					echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
-					sleep 1
-					service gdm3 start 2>/dev/null
-					if [ -f /root/.desktop_autologin ]; then
-						rm /root/.desktop_autologin
-					else
-						(sleep 20; sed -i "s/AutomaticLoginEnable.*/AutomaticLoginEnable = false/" /etc/gdm3/custom.conf) &
-					fi
-					# logout if logged at console
-					[[ -n $(who -la | grep root | grep tty1) ]] && exit 1
+	# 				# Let the user reboot now otherwise start desktop environment
+	# 				printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+	# 				printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
 
-				fi
+	# 			elif [ -z "$ConfigureDisplay" ] || [ "$ConfigureDisplay" = "n" ] || [ "$ConfigureDisplay" = "N" ]; then
 
-	else
+	# 				echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
+	# 				sleep 1
+	# 				service gdm3 start 2>/dev/null
+	# 				if [ -f /root/.desktop_autologin ]; then
+	# 					rm /root/.desktop_autologin
+	# 				else
+	# 					(sleep 20; sed -i "s/AutomaticLoginEnable.*/AutomaticLoginEnable = false/" /etc/gdm3/custom.conf) &
+	# 				fi
+	# 				# logout if logged at console
+	# 				[[ -n $(who -la | grep root | grep tty1) ]] && exit 1
 
-		# Display reboot recommendation if necessary
-		if [[ -f /var/run/resize2fs-reboot ]]; then
-			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
-		fi
+	# 			fi
 
-	fi
+	# else
+
+	# 	# Display reboot recommendation if necessary
+	# 	if [[ -f /var/run/resize2fs-reboot ]]; then
+	# 		printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+	# 		printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+	# 	fi
+
+	# fi
 
 fi
